### PR TITLE
Feat WIP: add set-balance function in ipo pallet

### PR DESCRIPTION
**Pull request by SHA888**
- Add `set_balance` function in ipo balance
- [Need help] implement more logic for free and reserved balance.

### CODE REVIEW

**Comment by Invarchitect** [comment]
The balance should automatically be set to 10000, per IP Set.

When you say set_balance, what is this referring to?

**Comment by SHA888** [comment]
I was thinking this is how the root account sets the balance. The 10_000 IPO per IPS will be implemented in the InvArch-node runtime. Cmiiw

**Comment by Invarchitect** [comment]
I see, my mistake 😅 You're right. 

However, I wonder if this should be a function of the IPO pallet itself, or of the DEV pallet down the road. This way, the DEV pallet can focus on the IPO allocation logic. 

The main point of the IPO pallet, I believe, should be to establish/create the IPO tokens themselves, and ensure that their pegged to an IP Set.

Thoughts?

**Comment by SHA888** [comment]
@Invarchitect Yes I thought so. In this way, this library in general could be implemented composable to any node runtime custom logic.

**Review by arrudagates — APPROVED** [review]
Looks good to me

**Comment by SHA888** [comment]
@arrudagates should we merge this first and then get back here to make any changes / update for it later on when needed?

**Review by Invarchitect — APPROVED** [review]
`bind` and `unbind` are more for $VARCH, but we can explore further.

**Comment by Invarchitect** [comment]
The bind function should allow

**Pull request merged**
